### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by ladtopi** [jensjvh/ot-harjoitustyo#1]
**_Projekti kloonattu 05.12.2024 kello 13:55._**

Projekti vaikuttaa lähteneen varsin hyvin käyntiin. Sovellus oli helppo saada toimimaan, testit menevät läpi, ja koodi on suurimmaksi osaksi hyvin jäsenneltyä ja helppolukuista. Tässä on myös kaikki oleelliset palikat jo mukana käyttöliittymästä tietokantaan. 🚀 

Muutamia teknisiä ja laadullisia huomioita:
* `BudgetService`-luokka hoitaa nyt hieman moninaisia tehtäviä varsinaisten budjettien käpistelystä autentikointiin ja käyttäjien luomiseen. Luokka ei siis ole kovin koherentti.
* Käyttäjän syötteitä ei validoida mitenkään budjettirivejä luodessa. On esimerkiksi mahdollista tehdä rivi päivämäärällä "1", tai summalla "kolme".
* Sovellus yhdistää aina samaan tietokantaan riippumatta kontekstista. Tämän johdosta testien ajaminen sovelluksen käyttämisen jälkeen poistaa kaiken käyttäjien datan (koska testien teardownit tyhjentävät kannan). Koodiin sinänsä rakennettua riippuvuuksien injektointimahdollisuutta kannattaisi ehdottomasti hyödyntää testeissä niin, että testejä ajettaessa komponenteille syötettäisiin testitietokanta. SQLitessä tämä on helppo toteuttaa esimerkiksi käyttämällä connection stringiä `:memory:`, jolloin tietokanta sijaitsee puhtaasti muistissa. ([linkki dokumentaatioon](https://www.sqlite.org/inmemorydb.html))

Korkeamman tason huomiona, että sovelluksen tarjoama toiminnallisuus on vielä hyvin ohkaista. Sovellus ei esimerkiksi anna mahdollisuutta tarkastella koko budjetin yhteissummaa, eikä se anna mahdollisuutta tarkastella kirjattua budjettia kategorioittain. Näiltä osin myös perusversion vaatimusmäärittely vaikuttaa aavistuksen puutteelliselta. Perusversion vaatimusmäärittelyyn on kirjattu lähinnä datan syöttämistä, mutta käyttäjälle sovelluksen arvo muodostunee paljolti syötettyjen tietojen tarkastelusta. Toki projekti on kesken, ja vaikuttaa että jatkokehitys-osastolle on määritetty monia kivoja ja käyttäjälle aidosti hyödyllisiä toiminnallisuuksia.

**Comment by jensjvh** [comment]
Kiitos! Hyviä ehdotuksia. Korjasin joitain näistä palautusta varten, ja pidän muut kommentit mielessä projektin loppua varten.
